# Generated by Django 5.2.3 on 2025-06-14 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('projetos', models.ManyToManyField(related_name='funcionarios', to='gerencia.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='EstruturaAnaliticaProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_tarefas', models.IntegerField(default=0)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencia.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='QuadroKanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('numero_de_cards', models.IntegerField(default=0)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencia.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='CardKanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(max_length=70)),
                ('status', models.CharField(default='para fazer', max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=140, null=True)),
                ('data_de_entrega', models.DateField()),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencia.quadrokanban')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('conteudo', models.TextField(max_length=3000)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencia.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='TarefaEAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('descricao', models.CharField(max_length=140)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='gerencia.projeto')),
                ('responsaveis', models.ManyToManyField(related_name='tarefas', to='gerencia.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='TermoAberturaProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('documento', models.FileField(upload_to='documentos/')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencia.projeto')),
            ],
        ),
    ]
