# Generated by Django 5.2.3 on 2025-06-14 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefaeap',
            name='eap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gerencia.estruturaanaliticaprojeto'),
            preserve_default=False,
        ),
    ]
