# Generated by Django 5.2.3 on 2025-06-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0002_tarefaeap_eap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefaeap',
            name='descricao',
            field=models.TextField(max_length=2000),
        ),
    ]
