# Generated by Django 5.2.3 on 2025-06-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0004_estruturaanaliticaprojeto_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefaeap',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='tarefaeap',
            name='descricao',
            field=models.CharField(max_length=70),
        ),
    ]
