# Generated by Django 5.2.3 on 2025-06-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0006_remove_cardkanban_descricao_cardkanban_responsaveis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardkanban',
            name='data_de_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
