# Generated by Django 5.2.3 on 2025-06-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0008_alter_cardkanban_responsaveis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardkanban',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, related_name='tarefas', to='gerencia.funcionario'),
        ),
    ]
