# Generated by Django 5.2.3 on 2025-06-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0009_alter_cardkanban_responsaveis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termoaberturaprojeto',
            name='titulo',
        ),
    ]
